name: Code style check

on: [push, pull_request]

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 12

  job_misspell:
    name: Check misspellings
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check misspellings
        uses: codespell-project/actions-codespell@bcf481f4d5cce7b92b65f05aebe8f552d4f1442c
        with:
          builtin: clear,rare
          check_filenames: true
          ignore_words_list: afterall
